### ISSUE TITLE
Button to cloning a photos

### ISSUE THREAD

**Issue by aleksey-su** [Polarrco/polarr_chrome_web_support#10]
Add button for cloning a photos in more menu.
![image](https://cloud.githubusercontent.com/assets/485892/17002172/bf50f06e-4ed2-11e6-866d-e1896d1c4cc8.png)

**Comment by kpaddie** [comment]
Hi Aleksey,

Thank you so much for your feedback! We will consider this tool for future development.

Best,

-Polarr team
