### ISSUE TITLE
Bought Mac version... Can I unlock web version?

### ISSUE THREAD

**Issue by jdsimcoe** [Polarrco/polarr_chrome_web_support#11]
I really love being able to use the Pro features of the web version. I bought the Mac app. I shouldn't have to pay $20 additional to access the web version. How do you guys handle this?

**Comment by kpaddie** [comment]
Hi there,

As the apps are on separate platforms, they must be unlocked separately. We are currently working on system that will integrate the different platforms, so stay tuned. 

Best,

-Polarr team

**Comment by jdsimcoe** [comment]
When is the new version of Polarr coming out?

>

**Comment by kpaddie** [comment]
Hi,

We do not yet have an ETA for this release. It is under development.

Best,

-Polarr team
