### ISSUE TITLE
Unlock code validation

### ISSUE THREAD

**Issue by lz0** [Polarrco/polarr_chrome_web_support#12]
Got to start of with giving you guys the truck load of credit where credit is due. Amazing work with this multi-platforming photo-editing app you've created.

I bought a license for your software back in February and been using it happily on both my android device and my Chromebook via the chrome web store. My problem for which I write this Issue here is that of my code validation. I've reinstalled my Chromebook a few times over the days since of February when I installed it first. Mainly due to me switching from developer mode and not which clears all the userdata on the Chromebook. This for some reason also clears all the userdata of Polarr and requires me to feed in my bought key for re-validation. On the validation page in the app it's stated clear that you may only use the code for 3 computers. My belief is that for every time I've feed in the code in the app for restart it's counted down on those 3 times even though I'm still on the computer.

I don't know if this is the place, it is certainly a place for me to state the issue and my opinion that I would like to see a fix in the way Polarr managed validated keys per computer and that the app should recognize my computer as a computer and not as per every reinstall a new computer. I don't want to have to spend money on a new key for simply I've bought one already.

For extra details on reproducing of the issue
please write below

well met
lz0

**Comment by kpaddie** [comment]
Hi Iz0,

Thank you for bringing this issue to our attention, it is very useful, and we will be looking into it.

In the meantime, while we do not yet have a workaround, we suggest emailing support@polarr.co when you need a new code. Here is a new code for you: NFG9A-CN6ED-K59L9-BY268-S5QV4

We try to respond to all emails to support@polarr.co within 48 hours.

Best,

-Polarr team
