### ISSUE TITLE
Thumbnail of edited photo shows original image

### ISSUE THREAD

**Issue by 3dbloke** [Polarrco/polarr_chrome_web_support#13]
Running Polarr in Chrome on Windows 10, when I export an edited JPEG to my local disk, the thumbnail shown in Windows File Explorer (with the setting `View > Large icons`) is of the **original** image, rather than the updated one.

**Comment by bwang29** [comment]
We figured out this is a sRGB and RGB encoding issue, fixing soon early Jan.
