### ISSUE TITLE
photoeditor vs v3; accounts

### ISSUE THREAD

**Issue by shinmai** [Polarrco/polarr_chrome_web_support#14]
I tried to activate my key for Polarr on the web version, so I went to polarr.co, selected Web Browser and was taken to photoeditor.polarr.co. There I created an account, was greeted with a message "Your account does not have full feature access". After that I entered the key. Now I have full access in one browser, but I have no idea what that is tied to, because when I try to login in another browser, I get the same "Your account does not have full feature access" error. Also, selecting "Get license" from the menu, takes me to a landing page about Polarr for Web, where choosing "Open Polarr Photo Editor" takes me to v3.polarr.co, where there are no controls about entering license keys.

I'm wholly confused as to what the relationship between photoeditor and v3 is, what my currently unlocked license is tied to (I'm assuming a cookie?), and how to get it tied to an account so I can actually use it should I change browsers or something.

**Comment by kpaddie** [comment]
Hi Shinmai,

Thanks for alerting us to this issue!

"Open Polarr Photo Editor" should have taken you to v4, the latest version of our web editor. It was a mistake that it redirected to v3, we have fixed that now. v4 is the same as as photoeditor.polarr.co.

Can you email your purchase receipt to support@polarr.co? We want to figure out why you didn't have access on the other browser.

Best,

-Polarr team

**Comment by RiTCHiE007NL** [comment]
Yes, i would like to know this also. Is the license tied to a account? And if i activate the web browser version on my PC, can i use the same web browser version on my laptop also when i log into the same account or do i need to actvate it again?

**Comment by bwang29** [comment]
The current web version and Chrome are all synced in one account. Closing issue.
