### ISSUE TITLE
License Activation tied to account?

### ISSUE THREAD

**Issue by RiTCHiE007NL** [Polarrco/polarr_chrome_web_support#17]
I would like to know if the license it tied to a account? And what if i activate the photoeditor.polarr.co version, can it be used on other computers also?

**Comment by kpaddie** [comment]
Hi there,

Yes, licenses are tied to an account for most desktop versions of Polarr. Login should work across Web, Windows, and Chrome versions. 

Very best,
-Polarr team

**Comment by 3dbloke** [comment]
@kpaddie wrote:

> Login should work across Web, Windows, and Chrome versions.

Is this true? I have the Chrome licence and I understood this is not applicable to the Windows version.

**Comment by RiTCHiE007NL** [comment]
@3dbloke  Well on the windows version there is no way to login into your account because its not in the settings tab so i highly doubt that its possible but maybe with some updates it should be possible.

**Comment by kpaddie** [comment]
Hi,

For any issues in connecting licenses to activations, please email support@polarr.co, and we'll resolve your issue ASAP.

Best,

-Polarr team

**Comment by RiTCHiE007NL** [comment]
Oke, thank you for the reply and i emailed them to report the problems.

**Comment by bwang29** [comment]
License activation is now enabled across different platforms with Polarr email.
