### ISSUE TITLE
Brush mask not working like it should

### ISSUE THREAD

**Issue by RiTCHiE007NL** [Polarrco/polarr_chrome_web_support#19]
I would like to know if it should work like this or that its a bug? Because i cant seem to use the brush mask like in lightroom where it paints more consistent and its almost unusable. i have uploaded a video so you can see what im talking about that you can see here https://vid.me/RFsp  Hope someone can tell me what im doing wrong or how i can fix this to get it working because to me a good working brush is a must to get the best out of my photo's.

**Comment by kpaddie** [comment]
Thanks so much for reporting this issue. To help us address it as best as we can, can you send info about your device year/model, and OS, along with what version of Polarr you are using, to support@polarr.co?

Best,

-Polarr team
