### ISSUE TITLE
Polarr chrome not exporting images

### ISSUE THREAD

**Issue by dsaronin** [Polarrco/polarr_chrome_web_support#2]
Description:
Imported and edited RAW (DSC_xxx.NEF) file on Google Drive.
Was able to have one image (JPG) exported; was saved to my local Chromebook drive.
But working with a set of four RAW files in Polarr, none successfully exported. Polarr hangs with the message: "Exporting DSC_0502.jpg" but never completes. Related: I was trying to speed things up by queueing export requests: once the "exporting" message appeared, I clicked on the next thumbnail, and initiated an export request for it. and so on for four images. But I cannot find any of the images either locally or on Google Drive. When I just try to export a single image and wait, the "exporting" message never resolves, even after waiting thirty minutes. I have reset my Chromebook, and still the same problem.

Environment:
Chromebook:
Version 50.0.2661.104 (64-bit)
Platform 7978.76.0 (Official Build) stable-channel gandof
Firmware Google_Gandof.6301.155.9

**Comment by bwang29** [comment]
This is related to issue https://github.com/Polarrco/polarr_chrome_web_support/issues/3 and will be addressed together.
