### ISSUE TITLE
Resolution problem with raw file (.RAF file from Fujifilm X30)

### ISSUE THREAD

**Issue by BirdyF** [Polarrco/polarr_chrome_web_support#21]
First, I like very much your software, easy and powerful. 
I have a new camera Fujifilm X30 and noticed that the raw file once loaded into Polarr is not used at its full resolution (2048x1536 instead of 4000x2664) I dont have this problem with the JPG file from the same camera.
Please find attached the same picture in the 2 formats to allow you to test.

Patrick 

![dscf5181](https://cloud.githubusercontent.com/assets/23250316/19991915/a79743b0-a274-11e6-8b58-0ba4fbd9a680.JPG)

[DSCF5181.RAF.ZIP](https://github.com/Polarrco/polarr_chrome_web_support/files/570472/DSCF5181.RAF.ZIP)

**Comment by kpaddie** [comment]
Hi Patrick,

Unfortunately, this is a side effect of the way Polarr handles RAW files, and cannot be reversed. We are happy to offer a refund if you email your original purchase receipt to support@polarr.co.

Best,

-Polarr team

**Comment by BirdyF** [comment]
Thanks for your quick answer.
Dont worry I am still very happy with Polarr on Chromebook. It is a nice
piece of software.

Best regards

Patrick

On Sunday, November 6, 2016, kpaddie <notifications@github.com> wrote:
> Hi Patrick,
>
> Unfortunately, this is a side effect of the way Polarr handles RAW files,
and cannot be reversed. We are happy to offer a refund if you email your
original purchase receipt to support@polarr.co.
>
> Best,
>
> -Polarr team
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/DMdsJWHIDLEOcS9QFnAuGgDX_MDOEIUDbJlI1DABYh3G7q11FLANJ3hFyMjKg_cMh2-aCpvN7g4Ab-MR_b2MPqQRNJ74Q239SVIWp26Jh65SDIhxpHdZaD0lkO7ivBR_dVAFjpgr8Md6FAT1oSycVgUn0-ftyQ=s0-d-e1-ft#https://github.com/notifications/beacon/AWLFjKRwkHH4qlExm1xewDj5N3jVLHUEks5q7Uz4gaJpZM4KpHcj.gif
>

-- 
Patrick FINKELSTEIN
+33 6 988 73 388
