### ISSUE TITLE
Polarr on ChromeOS won't load

### ISSUE THREAD

**Issue by voss** [Polarrco/polarr_chrome_web_support#3]
As title. The Polarr app loads up to about 75% then gets stuck, and after a little wait, shows the 

"Stuck? Clear Cache and Reload"

message. Clearing cache doesn't help. Waiting doesn't help either.

I'm using a Samsung Chromebook running ChromeOS Version 51.0.2704.37 beta, and is seems like everybody else reporting this on the [app download page](https://chrome.google.com/webstore/detail/polarr-photo-editor-3/djonnbgfieijldcieafgjcnhmpcfpmgg/support) in the Chrome Webstore, is running a similar version.

Could just be related to the beta-version of Chrome, but would be nice to have Polarr acknowledge that this is happening.

**Comment by tomhusband** [comment]
Yes, me too.  I'm on a Toshiba 2 running Chrome OS 51.0.2704.55 beta.  I'd really like to use Polarr but have un-installed it for the time being.

It would really be nice to hear back on this.

**Comment by zivbenster** [comment]
same here, Dell chromebook 13 7310 with core-m processor. chrome-os on beta channel:
Version 51.0.2704.55 beta (64-bit)
Platform 8172.39.0 (Official Build) beta-channel lulu
Firmware Google_Lulu.6301.136.57

**Comment by FireFighterTaz** [comment]
Same thing is happening with me as the OP

Asus Chromebook C300
Intel N2830 Processor

Version 51.0.2704.79 (64-bit)
Platform 8172.47.0 (Official Build) stable-channel quawks
Firmware Google_Quawks.5216.204.61

**Comment by tomhusband** [comment]
It's too bad we can't get a response here.

**Comment by ryancd** [comment]
Same here. Toshiba Chromebook running Chrome 51

**Comment by bwang29** [comment]
Hey everyone, sorry for the late response as we're wrapping up development for v4 for Polarr on Chrome/Mac/Windows. This is an issue with the way we cache and persist editing history and the expected new 4.0 release will come up end of this month. Sorry for the wait! If you already bought the app, you can send your receipt to support@polarr.co for a refund.

**Comment by voss** [comment]
Thanks for confirming @bwang29, will look forward to the 4.0 release of a great app, hopefully with a fix! (:

**Comment by tomhusband** [comment]
Yes, thanks @bwang29, but I'm not clear, will 4.0 fix this problem?

**Comment by sisim88** [comment]
I am also having trouble with the polarr app on my chromebook. It continues to ask me to clear the cache and reload. Hope this problem will be fixed soon.

**Comment by bwang29** [comment]
@voss @tomhusband @zivbenster @FireFighterTaz @ryancd Please try out 3.3.1 in store right now. It should fix it. 

For 4.0 we consider it is a new app (almost), and it will replace 3.0.

**Comment by lloyd1981** [comment]
Oh.
"_**This is an issue with the way we cache and persist editing history and the expected new 4.0 release will come up end of this month.**_"
Sorry to say but that is a poor excuse. You COULD do like big boy firms USED to do and put up a 404 with a message and a link to some sort of message file. All the web sites I built had escape routes and information packages.

**Comment by bwang29** [comment]
Most of these issues should be resolved in the current version of Polarr. Re-open if needed.
