### ISSUE TITLE
Anti-aliasing ?

### ISSUE THREAD

**Issue by lauwqui** [Polarrco/polarr_chrome_web_support#4]
Love you app, I'm hesitating to buy it now just because of one major problem. There is no anti-aliasing and it's making editing difficult. I suppose anti-aliasing asks a lot of ressources that the Chromebook might not support.. or maybe there is something to activate ?

I have a Chromebook CB5-311.

Thank you !

**Comment by bwang29** [comment]
We will introduce anti-aliasing settings, together with a significant overhaul of the windows app end of this month.
