### ISSUE TITLE
Not all button can be touch.

### ISSUE THREAD

**Issue by kreaninw** [Polarrco/polarr_chrome_web_support#6]
It appears not all button can be touch, including **HSL** (can't touch to select the color to adjust), any button in **Crop** tool (aspect ratio, rotate, flip), and **Save JPEG** or **Save PNG** button in Export menu. 

I hope it will be fixed soon as I just bought pro license even though I already knew this issue in free version. Windows 10 version doesn't have this issue but I feel like using Chrome. Thanks.

I am using Surface Pro 4 Core i7 256 GB.

**Comment by bwang29** [comment]
There will be a significant overhaul of the windows app end of this month. And we will address the touch events with a newly designed UI.
