### ISSUE TITLE
I bought the Pro features already

### ISSUE THREAD

**Issue by Kitsuami** [Polarrco/polarr_chrome_web_support#8]
I bought the pro features already (back when it was 4.99) and whenever I installed the program on any of my other computers, it would say "It seems you have bought something on this account already. Enjoy the Pro features.." or something like that. Either way, I cant use my version anymore because its telling me I have to still buy it. I really loved this program but I really don`t have 20$ to spend on something that I already bought. Theres the photo of the transaction.

![screenshot_3](https://cloud.githubusercontent.com/assets/20499154/16899490/e79aaad0-4bba-11e6-9770-4c89bc7da842.png)

**Comment by kpaddie** [comment]
Hello,

In this case, you may need to uninstall and reinstall the app. Here is a new code you can use up to 3 times to unlock pro features on your desktop devices: C4NYM-ELRQT-V7ZQW-W9X5E-2Q3M4

Best,
