### ISSUE TITLE
No Unlock Code

### ISSUE THREAD

**Issue by gettingaround** [Polarrco/polarr_chrome_web_support#9]
I just sent $20 for the Pro version. I confirmed my email. I open Polarr in a Chrome tab and I can sign in, however when I try to open the Chrome app, it asks for an unlock code. Please, where do I find the unlock code. Will this work for the IOS/Android apps, or do I have to buy those separately? 

Have a great day!

**Comment by kpaddie** [comment]
Hello,

Your code may have been intercepted by a "junk" or "spam" folder. Here is a replacement code for you: 6GLSR-GUBS9-NMN2R-7YYWE-4BSB7

Best,

-Polarr team
